name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-gateway-host:
    name: Build Gateway Host (ESP32-S3)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Gateway Host
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32s3
          path: 'gateway/host'

  build-gateway-rcp:
    name: Build Gateway RCP (ESP32-H2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build RCP
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32h2
          path: 'gateway/rcp'

  build-node:
    name: Build Node (ESP32-H2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build Node
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.3.1
          target: esp32h2
          path: 'node'
